# Generated by Django 4.2.19 on 2025-02-27 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [ 
        ("arches_her", "0001_initial"),
        ("models", "9945_file_thumbnail_bin_file_thumbnail_text")
    ]

    operations = [
    ]
