# Generated by Django 4.2.19 on 2025-02-27 18:06

from django.db import migrations, models
import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('models', '9945_file_thumbnail_bin_file_thumbnail_text'),
        ('aher_project', '0003_add_tile_display_function'),
    ]

    operations = [
        migrations.CreateModel(
            name='TileEmbedding',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('models.tilemodel',),
        ),
        migrations.CreateModel(
            name='TileEmbeddingDocument',
            fields=[
                ('tileembeddingid', models.UUIDField(default=uuid.UUID('7e9a0022-6de5-487c-bbfc-a2315f75e6b6'), primary_key=True, serialize=False)),
                ('document', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1536)),
                ('tile', models.ForeignKey(db_column='tileid', null=True, on_delete=django.db.models.deletion.CASCADE, to='models.tilemodel')),
            ],
            options={
                'db_table': 'tile_embeddings',
                'managed': True,
                'indexes': [pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='idx_tile_embedding', opclasses=['vector_l2_ops'])],
            },
        ),
    ]
