# Generated by Django 4.2.19 on 2025-02-28 01:27

from django.db import migrations, models
import pgvector.django.indexes
import pgvector.django.vector
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('aher_project', '0004_add_tile_embedding'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='tileembeddingdocument',
            name='idx_tile_embedding',
        ),
        migrations.AlterField(
            model_name='tileembeddingdocument',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=768),
        ),
        migrations.AlterField(
            model_name='tileembeddingdocument',
            name='tileembeddingid',
            field=models.UUIDField(default=uuid.UUID('d390b4ab-0a59-411b-895f-ebc76bc19c2a'), primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='tileembeddingdocument',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='idx_tile_embedding', opclasses=['vector_cosine_ops']),
        ),
    ]
