# Generated by Django 4.2.19 on 2025-02-28 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aher_project', '0005_remove_tileembeddingdocument_idx_tile_embedding_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tileembeddingdocument',
            name='tileembeddingid',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
