# Generated by Django 4.2.20 on 2025-03-08 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '9945_file_thumbnail_bin_file_thumbnail_text'),
        ('aher_project', '0008_add_resourceinstance_to_tileembedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tileembeddingdocument',
            name='resourceinstance',
            field=models.ForeignKey(db_column='resourceinstanceid', null=True, on_delete=django.db.models.deletion.CASCADE, to='models.resource'),
        ),
    ]
